<<<<<<< Updated upstream
#pragma config(Motor, motor1, , tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//
#define WHEEL_MOTOR_SPEED 100
#define ARM_MOTOR_SPEED 100
#define CLAW_MOTOR_SPEED 100

task main() {
  int button_pressed = 0;
  while (1) {
    if (button_pressed) {
      setMotorSpeed(motor1, 25);
    } else {
      setMotorSpeed(motor1, 0);
    }
  }
}
=======
#pragma config(Sensor, dgtl1,  But1,           sensorTouch)
#pragma config(Motor,  port1,           Drive1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Drive2,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define WHEEL_SPEED 100
#define ARM_SPEED 100
#define CLAW_SPEED 100

enum systemPhase {
	idle = 0,
	moveFore,
	pickup,
	moveBack,
	makeEgg
};

task main()
{
	systemPhase phase = idle;

	while(true){
		switch (phase) {
			case idle:
				if (SensorValue[But1])
					phase = moveFore;
				break;

			case moveFore:
				motor[Drive1] = WHEEL_SPEED;
				motor[Drive2] = WHEEL_SPEED;
				break;

			case pickup:
				break;

			case moveBack:
				break;

			case makeEgg:
				break;
		}
	}
}
>>>>>>> Stashed changes
