#pragma config(Motor, motor1, , tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//
#define WHEEL_MOTOR_SPEED 100
#define ARM_MOTOR_SPEED 100
#define CLAW_MOTOR_SPEED 100

task main() {
  int button_pressed = 0;
  while (1) {
    if (button_pressed) {
      setMotorSpeed(motor1, 25);
    } else {
      setMotorSpeed(motor1, 0);
    }
  }
}
