#pragma config(Motor,  motor1,           ,             tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int button_pressed = 0;
	while(1){
		if (button_pressed) {
			setMotorSpeed(motor1, 25);
		}
		else {
			setMotorSpeed(motor1, 0);
		}
	}
}
